void delay(int);
void limpaTela(void);
int Digito(char);
int validar_letra(char);
int validar_nome(char);
int validarcpf(char);
int validar_email(void);
int valida_data(int, int, int);
int validar_ramo(char);
int validar_tipo_de_consulta(char);
int validar_codConsulta(char);
int validar_horas(char);
